version: '3.8'

services:
  assistant_bot:
    build: .
    container_name: assistant_bot
    restart: always
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
